name: CI

on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        env:
          TERRAFORM_WRAPPER: false # when enabled JSON output of Terraform Plan is not properly parsed
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION }}
          terraform_wrapper: ${{ env.TERRAFORM_WRAPPER }}

      - name: Ensure code is formatted
        run: terraform fmt -diff -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - uses: actions/cache@v4
        name: Cache TFLint plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5.0.0

      - name: Init TFLint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint

      - name: Pull Checkov image
        run: docker pull bridgecrew/checkov:latest

      - name: Scan code with Checkov
        run: |
          docker run \
            --name test-container \
            --tty \
            --rm \
            --volume $(pwd):/tf bridgecrew/checkov:latest \
            --directory /tf \
            --framework terraform \
            --check CKV_AZURE* \
            --soft-fail
