name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        env:
          TERRAFORM_WRAPPER: false # when enabled JSON output of Terraform Plan is not properly parsed
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION }}
          terraform_wrapper: ${{ env.TERRAFORM_WRAPPER }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: |
          ACCESS_KEY=$(az storage account keys list \
            --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --query "[0].value" | tr -d '"')

          terraform init -backend-config="access_key=${ACCESS_KEY}"
        env:
          STORAGE_ACCOUNT_NAME: stterraformwozorio

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan -input=false
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}

      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

      - name: Pull Checkov image
        run: docker pull bridgecrew/checkov:latest

      - name: Scan Terraform Plan with Checkov
        run: |
          terraform show -json tfplan | jq '.' > tfplan.json
          docker pull bridgecrew/checkov:latest
          docker run \
            --tty \
            --volume "$(pwd)":/tf bridgecrew/checkov:latest \
            --file /tf/tfplan.json \
            --framework terraform_plan \
            --check CKV_AZURE* \
            --soft-fail

  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: playground
    needs: terraform_plan

    steps:
      - uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        env:
          TERRAFORM_WRAPPER: false # when enabled JSON output of Terraform Plan is not properly parsed
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION }}
          terraform_wrapper: ${{ env.TERRAFORM_WRAPPER }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: |
          ACCESS_KEY=$(az storage account keys list \
            --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --query "[0].value" | tr -d '"')

          terraform init -backend-config="access_key=${ACCESS_KEY}"
        env:
          STORAGE_ACCOUNT_NAME: stterraformwozorio

      - uses: actions/download-artifact@v5
        with:
          name: tfplan

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
